---
- name: "Apache installation using docker"
  hosts: prod
  become: true
  pre_tasks:
    - name: Installation EPEL-Release
      package: name=epel-release state=present
      when: ansible_distribution == "CentOS"
    - name: Download pip script
      get_url:
        url: https://bootstrap.pypa.io/pip/2.7/get-pip.py
        dest: /tmp/get-pip.py
    - name: Install python-pip
      ansible.builtin.command: python2.7 /tmp/get-pip.py
    - name: Installation pip
      yum: name=python-pip state=present update_cache=yes
    - name: Installation docker-py
      pip: name=docker-py
  tasks:
    - name: Create Apache container
      docker_container:
        name: webapp
        image: httpd
        ports:
          - "80:80"
